apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  replicas: 1
  selector:
    io.kompose.service: api-gateway
  template:
    metadata:
      labels:
        io.kompose.network/finalproject-it460-default: "true"
        io.kompose.service: api-gateway
    spec:
      containers:
        - env:
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY
              value: ' TRACE'
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          image: ' '
          name: api-gateway
          ports:
            - containerPort: 8080
              hostPort: 8181
              protocol: TCP
            - containerPort: 8181
              protocol: TCP
      restartPolicy: Always
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - api-gateway
        from:
          kind: ImageStreamTag
          name: api-gateway:latest
      type: ImageChange
