apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: chahinej/api-gateway
      name: latest
      referencePolicy:
        type: ""
