apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: broker
  name: broker
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: confluentinc/cp-kafka:7.0.1
      name: 7.0.1
      referencePolicy:
        type: ""
