apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: discovery-server
  name: discovery-server
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: chahinej/discovery-server:latest
      name: latest
      referencePolicy:
        type: ""
