apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: grafana/grafana-oss:8.5.2
      name: 8.5.2
      referencePolicy:
        type: ""
