apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: keycloak
  name: keycloak
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: quay.io/keycloak/keycloak:18.0.0
      name: 18.0.0
      referencePolicy:
        type: ""
