apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: keycloak-mysql
  name: keycloak-mysql
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: mysql:5.7
      name: "5.7"
      referencePolicy:
        type: ""
