apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: mongo:4.4.14-rc0-focal
      name: 4.4.14-rc0-focal
      referencePolicy:
        type: ""
