apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: order-service
  name: order-service
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: chahinej/order-service:latest
      name: latest
      referencePolicy:
        type: ""
