apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe -f docker-compose.yml convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: postgres-order
  name: postgres-order
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres-order
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe -f docker-compose.yml convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/finalproject-it460-default: "true"
        io.kompose.service: postgres-order
    spec:
      containers:
        - args:
            - -p
            - "5431"
          env:
            - name: PGDATA
              value: /data/postgres
            - name: POSTGRES_DB
              value: order-service
            - name: POSTGRES_PASSWORD
              value: mysql
            - name: POSTGRES_USER
              value: lechaa
          image: postgres
          name: postgres-order
          ports:
            - containerPort: 5431
              hostPort: 5431
              protocol: TCP
          volumeMounts:
            - mountPath: /data/postgres
              name: postgres-order-claim0
      restartPolicy: Always
      volumes:
        - name: postgres-order-claim0
          persistentVolumeClaim:
            claimName: postgres-order-claim0
