apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: postgres-inventory
  name: postgres-inventory
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: postgres
      name: latest
      referencePolicy:
        type: ""
