apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: product-service
  name: product-service
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: chahinej/product-service:latest
      name: latest
      referencePolicy:
        type: ""
