apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    io.kompose.service: product-service
  name: product-service
spec:
  replicas: 1
  selector:
    io.kompose.service: product-service
  template:
    metadata:
      labels:
        io.kompose.network/finalproject-it460-default: "true"
        io.kompose.service: product-service
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          image: ' '
          name: product-service
      restartPolicy: Always
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - product-service
        from:
          kind: ImageStreamTag
          name: product-service:latest
      type: ImageChange
