apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: prometheus
  name: prometheus
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: prom/prometheus:v2.37.1
      name: v2.37.1
      referencePolicy:
        type: ""
