apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    io.kompose.service: zipkin
  name: zipkin
spec:
  replicas: 1
  selector:
    io.kompose.service: zipkin
  template:
    metadata:
      labels:
        io.kompose.network/finalproject-it460-default: "true"
        io.kompose.service: zipkin
    spec:
      containers:
        - image: ' '
          name: zipkin
          ports:
            - containerPort: 9411
              hostPort: 9411
              protocol: TCP
      restartPolicy: Always
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - zipkin
        from:
          kind: ImageStreamTag
          name: zipkin:latest
      type: ImageChange
