apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: zipkin
  name: zipkin
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: openzipkin/zipkin
      name: latest
      referencePolicy:
        type: ""
