apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: zookeeper
  name: zookeeper
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: confluentinc/cp-zookeeper:7.0.1
      name: 7.0.1
      referencePolicy:
        type: ""
